# Generated by Django 4.1.1 on 2022-09-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('CN101', 'INTRODUCTION TO COMPUTER PROGRAMMING'), ('CN102', 'PROGRAMMING PRACTICE I'), ('MA111', 'FUNDAMENTALS OF CALCULUS'), ('ME100', 'ENGINEERING GRAPHICS'), ('SC133', 'PHYSICS FOR ENGINEERS 1'), ('SC123', 'FUNDAMENTAL CHEMISTRY')], default='math', max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('student_id', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('academic_year', models.IntegerField()),
                ('num_seats', models.IntegerField()),
            ],
        ),
    ]
