# Generated by Django 4.1.1 on 2022-09-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='student_name',
            new_name='subject_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
