# Generated by Django 4.1.1 on 2022-09-16 11:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0002_rename_student_name_subject_subject_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.AddField(
            model_name='subject',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='enrolled_student',
            field=models.ManyToManyField(blank=True, related_name='Subject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='academic_year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
