# Generated by Django 4.1.1 on 2022-09-17 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_subject_id_subject_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='subject_name',
        ),
    ]
