# Generated by Django 4.1.1 on 2022-09-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_rename_subject_subject_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='enrolled_student',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('enroll_subject', models.ManyToManyField(blank=True, related_name='passengers', to='university.subject')),
            ],
        ),
    ]
