# Generated by Django 4.1.1 on 2022-09-17 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_enrolled_alter_student_enroll_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='num_seats',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
